<a href="https://colab.research.google.com/github/2025csshreyasckg-commits/DAV_4NI25CS186_github/blob/main/DAV_LAB1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print("hello world")

hello world

In [ ]:
import pandas as pd

In [ ]:
data = {
    "Name":["Anu","Rhaul","Kiran","Priya"],
    "Marks":[45, 67, 98, 62],
    "Attendence":[69, 84, 91, 76]
}
df = pd.DataFrame(data)

In [ ]:
df.head()

    Name  Marks  Attendence
0    Anu     45          69
1  Rhaul     67          84
2  Kiran     98          91
3  Priya     62          76

In [ ]:
df.tail()

    Name  Marks  Attendence
0    Anu     45          69
1  Rhaul     67          84
2  Kiran     98          91
3  Priya     62          76